# Generated by Django 5.2 on 2025-05-17 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PRINCIPAL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_PRINCIPAL.cliente'),
        ),
    ]
