# Generated by Django 5.2 on 2025-05-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PRINCIPAL', '0002_alter_agenda_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('merch', 'Merch'), ('comestible', 'Comestibles'), ('bebida', 'Bebidas'), ('belleza', 'Belleza')], max_length=20),
        ),
    ]
