# Generated by Django 5.2 on 2025-05-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PRINCIPAL', '0004_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Direccion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/perfiles/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
