# Generated by Django 5.2 on 2025-05-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PRINCIPAL', '0005_remove_cliente_direccion_cliente_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/perfiles/'),
        ),
        migrations.AddField(
            model_name='barbero',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/perfiles/'),
        ),
    ]
