# Generated by Django 5.2 on 2025-05-21 20:00
# Generated by Django 5.2.1 on 2025-05-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PRINCIPAL', '0006_administrador_foto_perfil_barbero_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
