# Generated by Django 5.2 on 2025-05-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PRINCIPAL', '0008_barberia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
