# Generated by Django 5.2 on 2025-05-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PRINCIPAL', '0009_alter_administrador_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbero',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
