# Generated by Django 5.2 on 2025-05-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PRINCIPAL', '0010_alter_barbero_salario_alter_servicio_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('apertura', models.TimeField()),
                ('cierre', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Barberia',
        ),
        migrations.AddField(
            model_name='persona',
            name='password_visible',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
