# Generated by Django 5.2 on 2025-06-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PRINCIPAL', '0011_horario_delete_barberia_persona_password_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion_barberia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(default='Lunes a Viernes: 9:00 - 18:00', max_length=100)),
                ('telefono', models.CharField(default='123-456-7890', max_length=15)),
                ('ubicacion', models.CharField(default='Calle Falsa 123, Ciudad', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('redes_sociales', models.CharField(default='https://facebook.com/barberia', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='password_visible',
        ),
    ]
