# Generated by Django 5.2 on 2025-06-11 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PRINCIPAL', '0012_configuracion_barberia_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='telefono',
        ),
        migrations.AddField(
            model_name='evento',
            name='barbero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_como_barbero', to='APP_PRINCIPAL.barbero'),
        ),
        migrations.AddField(
            model_name='evento',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_como_cliente', to='APP_PRINCIPAL.persona'),
        ),
    ]
