# Generated by Django 5.2 on 2025-06-18 20:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PRINCIPAL', '0013_remove_evento_nombre_remove_evento_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='APP_PRINCIPAL.cliente'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='evento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='APP_PRINCIPAL.evento'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='no_molestar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='puntuacion',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
