services:
  - type: web
    name: style-fresh
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn STYLE_FREESH.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: STYLE_FREESH.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: style-fresh.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: style-fresh-db
          property: connectionString

databases:
  - name: style-fresh-db
    plan: free
